name: CI Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * 1" # At 08:00 on Monday

jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - name: Setup .Net 7.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
      - uses: actions/checkout@v3
      - name: Retore
        run: dotnet restore --nologo src
      - name: Build
        run: dotnet build --no-restore --nologo --configuration Release src
      - name: Test
        run: dotnet test --nologo --no-build --configuration Release src

  code-style:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Setup .Net 7.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
      - name: Tool restore with .Net
        run: dotnet tool restore
      - name: Retore
        run: dotnet restore --nologo src
      - name: .Net Format
        run: dotnet format --no-restore --verify-no-changes -v diag src
